Removing exception specifications
zeroc-ice/ice pull request #1059
Opened 2020-09-23 19:04 UTC by RedTaylor

2020-09-23 19:53 UTC, pepone requested changes
There are a few changes that are unrelated to the PR, is better if we just remove exception specifications here, and make the other changes separately

2020-09-23 19:53 UTC, pepone commented on csharp/test/Ice/impl/Test.ice
> +    (byte r1, byte r2) opByte(byte p1, byte p2);
Changes in this file seems unrelated to the PR

2020-09-23 19:53 UTC, pepone commented on csharp/test/Ice/optional/Test.ice
> +        void opInt(int? i1);
Changes here and in other files of Ice/optional test seems unrelated to the PR

2020-09-23 19:53 UTC, pepone commented on csharp/test/Slice/escape/Clash.ice
> +    (string context, string current, string response,
Indentation here looks bogus and the changes is unrelated to removing exceptions specifications

2020-09-23 19:53 UTC, pepone commented on csharp/test/Slice/escape/Key.ice
> +    (tag(1) break? r1, tag(2) as? goto, tag(3) explicit* if,
Indentation looks wrong here, and change is unrelated to this PR

2020-09-30 18:07 UTC, closed without merging

2020-09-30 18:08 UTC, RedTaylor commented
Closing to fix branch