Fix Bugs in How 'slice2swift' Handled 'misc' Comment Components
zeroc-ice/ice pull request #3008
Opened 2024-10-29 23:55 UTC by InsertCreativityHere

This PR fixes #2088 (Adding `@remarks` to a doc comment caused `slice2swift` to generate uncompilable code).

That being said, I think #2088 is also just a strange bug since Slice has no support for `@remarks` comment tags...
All unrecognized tags (including `@remarks`) are put in a special `misc` field, the contents of which are just pasted on to the end of generated comments, because we don't know what else to do with them.

2024-10-29 23:56 UTC, InsertCreativityHere commented on cpp/src/slice2swift/SwiftUtil.cpp
> -        out << "///" << nl;
This was just backwards, causing us to generate:
```
/// therefore proper security precautions should be taken.
/// and be registered in an object blah blah.///

/// @remarks something.
```

2024-10-30 00:00 UTC, InsertCreativityHere commented on cpp/src/slice2swift/SwiftUtil.cpp
> -        writeDocLines(out, doc.misc, false);
This is the part that fixes #2088.

The `false` parameter here meant: "don't put a triple slash in front of this line`.
So this code would generate:
```
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    @remarks This is a test!
```
With no leading triple slash, which rightfully angered the compiler.

Now, we generate:
```
    /// - parameter current: `Ice.Current` - The Current object for the dispatch.
    ///
    /// @remarks This is a test!
```

2024-10-30 00:02 UTC, InsertCreativityHere commented on cpp/src/slice2swift/SwiftUtil.cpp
> -        writeDocLines(out, doc.misc, false);
This was arguably worse than #2088. It caused us to just slap the `@remarks` on whatever line we were already writing to. No compiler error, but a silent failure:
```
/// Process Methods:
///
///  - writeMessage: Write a message @remarks something.
```

2024-10-30 00:02 UTC, InsertCreativityHere commented on cpp/src/slice2swift/SwiftUtil.cpp
> +        out << nl << "///";
Added an extra newline to the comment, to be consistent with how we generate other sections. Also, I just think it looks better.

2024-10-30 00:04 UTC, InsertCreativityHere commented on swift/test/Slice/escape/Key.ice
We have 0 testing of `slice2swift`, so I wanted to at add _something_.

I manually checked the output of this to make sure it looked good, and it will catch future errors which might introduce un-compilable code.

2024-10-30 12:47 UTC, externl approved these changes

2024-10-30 14:55 UTC, bernardnormier requested changes
This is not a good fix.

> All unrecognized tags (including @remarks) are put in a special misc field, 

This is an unexpected and unreasonable behavior, and we should not keep it and try it to make somewhat more correct.

The reasonable behavior for unknown tags is to:
a) fail
or
b) issue a warning and ignore the tag and associated text entirely

When I opened this issue, I was under the impression we supported the `@remarks` tag. Just like we support the `@deprecated` tag even though it's not documented.

Also, it's good to add tests, but please don't add the test to an unrelated test!

2024-10-30 16:30 UTC, InsertCreativityHere commented
No surprise to anyone, I think option B is the right way to go here.
I started mocking up an implementation, but it quickly goes beyond the scope of this PR.
Really what you're asking for is #2998, which I whole-heartedly agree we should implement,
but is a bigger project. So I'm just going to close this PR for now.

2024-10-30 16:30 UTC, closed without merging